[package]
name = "sp-core-ss58-example"
version = "0.1.0"
edition = "2021"

[dependencies]
sp-core = { version = "6.0.0", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.25" }